### ISSUE TITLE
Pushing to new Version

### ISSUE THREAD

**Issue by daMihe** [JordanRobinson/android-color-picker#2]
Hi Jordan,

thanks for making the AOSP-Picker available. Would you mind updating it? This should be easy as only language files were updated since the current master of your repository. More languange support is always better.

Thanks.

**Comment by jordanrobinson** [comment]
Hi there daMihe,

Sure, I'll make sure to update it as soon as I get a chance (probably within the next week or so).

Hope that's okay.

Thanks,
Jordan

**Comment by daMihe** [comment]
Hi Jordan,

yes sure it's okay.

Thanks for your quick reaction,
Michael

**Comment by jordanrobinson** [comment]
I've now updated to the latest version 🎉 

Please let me know if any issues but for now I'll close this off.

Thanks,
Jordan

**Comment by daMihe** [comment]
Thanks for your effort. I'm sorry to say i can't use it. Gradle simply can't resolve it. 1.0.1 works but not version 1.0.2. If looking to the bintray maven at https://dl.bintray.com/jordanrobinson/maven/uk/co/jordanrobinson/android-color-picker/ i can see inside 1.0.1 more files (`-javadoc.jar`, `-sources.jar`, `.pom`) than in 1.0.2. This may be the cause for it (especially pom-file?).

- Michael

**Comment by jordanrobinson** [comment]
Ah, sorry! Bintray changed their upload process and interface, so I wasn't sure if I'd done it right.

I've manually uploaded a new pom, are you okay to try it now and let me know?

Thanks,
Jordan

**Comment by daMihe** [comment]
Thank you, now it works fine. Just for your reference: i'm/we're using it here: https://bitbucket.org/frigus02/car-report (PR there is ready to include...)

Thanks again for your quick reaction,
Michael

**Comment by jordanrobinson** [comment]
Great! Glad to help 😄
